# -*- coding: utf-8 -*-
"""BeautifulSoup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dtf5fogFf8Y9TZMGDLnHlGwcptqap_yC
"""

pip install requests beautifulsoup4 pandas lxml

import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime

URL = "https://www.amazon.in/iPhone-Air-256-GB-Promotion/dp/B0FQFBDQJ1/ref=sr_1_1_sspa?crid=12PCSMVPDKB6U&dib=eyJ2IjoiMSJ9.1B-94AKUGk6JAqOAFCN2YUsSds_mnMdNw3eVNyx5ChJdv-CA6SlYNhORAHlKbBzp0YQmblped_cMi0I6Y4nvmAmACETjJ91wrfGAOmKO2D2_eGU7jCiKNt9KmCToZPtJlSPTJ6w5RCt_Y8vtUGCg6XJRQ-LX88BaASLIF34owsdwn7f3-kD3t-V2vwELfTt0RpxtAmdqO4-bK2XpApNmH693tYLfObR_7YgnzwBFFfA.8xJ7XZx7_KGwnJ3y76tSj8nd4B4RAVgjsI5em2XeXag&dib_tag=se&keywords=iphone+17&qid=1778217011&sprefix=ipjhone+1%2Caps%2C411&sr=8-1-spons&aref=RZV09fQlxc&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1"

headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept-Language" : "en-US,en;q=0.5"
}

response = requests.get(URL, headers=headers)
soup = BeautifulSoup(response.content, "lxml")
title = soup.find(id="productTitle")

if title:
  product_name = title.get_text(strip=True)
else:
  product_name = "Not found"

price = soup.find("span",class_="a-price-whole")

if price:
  product_price = price.get_text(strip=True)
else:
  product_price = "Not found"

now = datetime.now()

print("Product name: ",product_name)
print("Product price: ",product_price)
print("Date: ",now)

data = {
    "Product name": [product_name],
  "Product price": [product_price],
  "Date": [now]
}

df = pd.DataFrame(data)
df.to_csv("amazon.csv",index=False)
print("Data saved to amazon.csv")

